name: Example
on:
  merge_group:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Use Github Registry
        run: julia -e 'using Pkg; Pkg.Registry.rm("General"); Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"))'
      - name: Install Dependencies
        run: julia --project=examples/ -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate();'
      - name: Run Tests
        run: julia --project=examples/ examples/example.jl
